#!/usr/bin/env bash
#
#if [ ! -f "/etc/passwd" ]; then
#    echo "Error: /etc/passwd file not found."
#    exit 1
#fi
#echo "--- User Information from /etc/passwd ---"
#echo "Username           User ID           Home Directory"
#echo "---------------------------------------------------"
#while read -r line; do echo "$line" | cut -d: -f1,3,6;
#	    printf "%-18s %-15s %s\n" "$username" "$uid" "$home_directory"
#done < /etc/passwd
#echo "---------------------------------------------------"
#!/usr/bin/env bash

